config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :wentries
    root 'wentries#index'
  end
  get 'charts/expence_income' => 'charts#expence_income', :as => :expence_income_charts
  get 'charts/income' => 'charts#income', :as => :income_charts
  get 'charts/expense' => 'charts#expense', :as => :expense_charts

  
  
  
  
end

app/models/wentry.rb
class Wentry < ActiveRecord::Base
  
  scope :ic, -> (ic) {where ic: ic}
  scope :from_date, -> (date) {where("created_at >= (?)", Date.civil(date[:year].to_i, date[:month].to_i, date[:day].to_i).to_datetime)}
  scope :to_date, -> (date) {where("created_at <= (?)", Date.civil(date[:year].to_i, date[:month].to_i, date[:day].to_i).to_datetime+1)}
  
  monetize :amount, as: 'price'
  
  validates :amount, numericality: {greater_than_or_equal_to: 1}
  validates :category, :ic, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_i18n_locale_from_params
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
    def set_i18n_locale_from_params
      if params[:locale]
        if I18n.available_locales.map(&:to_s).include?(params[:locale])
          I18n.locale = params[:locale]
        else
          flash.now[:notice] = 
            "#{params[:locale]} translation not available"
          logger.error flash.now[:notice]
        end
      end
    end

    def default_url_options
      { locale: I18n.locale }
    end
  
  
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
   def expense_income
    render json: Wentry.group(:ic).sum(:amount) 
  end
   def income
    render json: Wentry.where("ic = 'Income'").group(:category).sum(:amount) 
  end
   def expense
    render json: Wentry.where("ic = 'Expense'").group(:catogory).sum(:amount) 
  end
end

app/controllers/wentries_controller.rb
class WentriesController < ApplicationController
  before_action :set_wentry, only: [:show, :edit, :update, :destroy]

  # GET /wentries
  # GET /wentries.json
  def index
    if params[:set_locale]
      redirect_to wentries_url(locale: params[:set_locale])
    else
      @wentries = Wentry.where(nil)
      @wentries = @wentries.ic(params[:ic]) if params[:ic].present?
      @wentries = @wentries.from_date(params[:from_date]) if params[:from_date].present?
      @wentries = @wentries.to_date(params[:to_date]) if params[:to_date].present?
    end
    
  end


  # GET /wentries/1
  # GET /wentries/1.json
  def show
  end

  # GET /wentries/new
  def new
    @wentry = Wentry.new
  end

  # GET /wentries/1/edit
  def edit
  end

  # POST /wentries
  # POST /wentries.json
  def create
    @wentry = Wentry.new(wentry_params)

    respond_to do |format|
      if @wentry.save
        format.html { redirect_to @wentry, notice: 'Wentry was successfully created.' }
        format.json { render :show, status: :created, location: @wentry }
      else
        format.html { render :new }
        format.json { render json: @wentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wentries/1
  # PATCH/PUT /wentries/1.json
  def update
    respond_to do |format|
      if @wentry.update(wentry_params)
        format.html { redirect_to @wentry, notice: 'Wentry was successfully updated.' }
        format.json { render :show, status: :ok, location: @wentry }
      else
        format.html { render :edit }
        format.json { render json: @wentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wentries/1
  # DELETE /wentries/1.json
  def destroy
    @wentry.destroy
    respond_to do |format|
      format.html { redirect_to wentries_url, notice: 'Wentry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wentry
      @wentry = Wentry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wentry_params
      params.require(:wentry).permit(:category, :amount, :ic)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wentries_helper.rb
module WentriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My spendings wallet</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='<%= controller.controller_name %>'>
    <div id="main-container" class="container">
      <div class="row">
	<div class="col-xs-3">
          <div class="row">
            <h3><%= t('.menu_html') %></h3>
          </div>
          <ul class="list-unstyled">
            <li><%= link_to t('.expenses'), controller: 'wentries', action: 'index', ic: 'Expense' %></li>
            <li><%= link_to t('.income'), controller: 'wentries', action: 'index', ic: 'Income' %></li>
            <li><%= link_to t('.summary'), controller: 'wentries', action: 'index' %></li>
            <li><a href='https://www.facebook.com/sharer/sharer.php?u=URL'><%= t('.facebook') %></a></li>
          </ul>
          <div class="row">
            <div class="col-xs-6">
              <%= form_tag wentries_path, method: 'get', class: 'locale' do %>
                <%= select_tag 'set_locale',
                  options_for_select(LANGUAGES, I18n.locale.to_s),
                  class: 'form-control',
                  onchange: 'this.form.submit()'%>
                <%= submit_tag 'Ok' %>
                <%= javascript_tag "$('.locale input').hide()" %>
              <% end %>
            </div>
          </div>
	</div>
	<div class="col-xs-9">
	  <%= yield %>
	</div>
      </div>
    </div>
  </body>
</html>

app/views/wentries/_date_filter_form.html.erb
<div class="row">
  <%= form_tag(wentries_path, method: "get", html: {class: 'form-inline'}) do %>
    <div class="field form-group">
      <%= label nil, t('.from_date'), class: 'col-xs-1 control-label' %>
      <div class="col-xs-4">
        <%= select_date Date.today, prefix: :from_date %>
      </div>
    </div>
    <div class="field form-group">
      <%= label nil, t('.to_date'), class: 'col-xs-1 control-label' %>
      <div class="col-xs-4">
        <%=  select_date Date.today, prefix: :to_date %>
      </div>
    </div>
    <div class="field form-group">
      <%= submit_tag t('.filter'), class: 'btn col-xs-1' %>
    </div>
  <% end %>
</div>

app/views/wentries/_form.html.erb
<%= form_for(@wentry, html: {class: 'form-horizontal'}) do |f| %>
  <% if @wentry.errors.any? %>
    <div class="row">
      <div class="col-sm-9">
        <div id="error_explanation">
          <dt><%= raw t('errors.template.header', count: @wentry.errors.count, model: t('activerecord.models.wentry')) %></dt>
          <ul>
          <% @wentry.errors.full_messages.each do |message| %>
            <li><%= raw message %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :category, t('.category_html'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-7">
      <%= f.text_field :category, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :amount_in_cents, t('.amount_in_cents'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-7">
      <%= f.text_field :amount, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :type, t('.type'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-7">
      <%= f.select :ic, ["Expense", "Income"], {}, {class: 'form-control'} %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit t('.create_entry'), class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wentries/_pie_chart.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<div class="row">
  <div class="col-sm-6">
    <%= pie_chart Wentry.group(:ic).sum(:amount) %>
  </div>
  <div class="col-sm-6">
    <%= pie_chart Wentry.group(:category).sum(:amount) %>
  </div>
</div>

app/views/wentries/edit.html.erb
<h1><%= t('.edit_entry') %></h1>

<%= render 'form' %>

<%= link_to t('.show'), @wentry %> |
<%= link_to t('.back_html'), wentries_path %>

app/views/wentries/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title_html') %></h1>

<%= render 'date_filter_form' %>

<%= render 'pie_chart' %>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('.category_html') %></th>
      <th><%= t('.amount') %></th>
      <th><%= t('.type') %></th>
      <th><%= t('.date') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wentries.each do |wentry| %>
      <tr class="<%= 'warning' if wentry.ic == 'Expense' %>">
        <td><%= wentry.category %></td>
        <td><%= number_to_currency(wentry.price) %></td>
        <td><%= wentry.ic %></td>
        <td><%= wentry.created_at.to_date %></td>
        <td><%= link_to t('.show'), wentry %></td>
        <td><%= link_to t('.edit'), edit_wentry_path(wentry) %></td>
        <td><%= link_to t('.destroy'), wentry, method: :delete, data: { confirm: t('.are_you_sure_html') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new_entry'), new_wentry_path, class: 'btn btn-success' %>

app/views/wentries/new.html.erb
<h1><%= t('.new_entry') %></h1>

<%= render 'form' %>

<%= link_to t('.back_html'), wentries_path %>

app/views/wentries/show.html.erb
<p id="notice"><%= notice %></p>

<dl>
  <dt><%= t('.category_html') %>:</dt>
  <dd><%= @wentry.category %></dd>

  <dt><%= t('.amount') %>:</dt>
  <dd><%= @wentry.amount %></dd>

  <dt><%= t('.type') %>:</dt>
  <dd><%= @wentry.ic %></dd>
</dl>

<%= link_to t('.edit'), edit_wentry_path(@wentry) %> |
<%= link_to t('.back_html'), wentries_path %>